# Generated by Django 4.2.6 on 2023-12-12 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('Colbun', 'Colbun'), ('Panimávida', 'Panimávida'), ('Maule sur', 'Maule sur'), ('La Guardia', 'La Guardia'), ('San Nicolas', 'San Nicolas'), ('Quinamavida', 'Quinamavida'), ('Rari', 'Rari'), ('Capilla Palacio', 'Capilla Palacio')], max_length=15)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Funcionario', 'Funcionario')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pago', models.CharField(max_length=20, unique=True)),
                ('pago', models.FloatField()),
                ('usuario_recibe_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to='sistema_web.user')),
                ('usuario_registra_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='sistema_web.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lectura', models.CharField(max_length=20, unique=True)),
                ('lectura', models.FloatField()),
                ('usuario_realiza_lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_realizadas', to='sistema_web.user')),
                ('usuario_toma_lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_tomadas', to='sistema_web.user')),
            ],
        ),
    ]
